server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: docker_containers
  pipeline_stages:
    - docker: {}
  loki_push_api:
    server:
      http_listen_port: 9081
    labels:
      job: docker_containers
    use_incoming_timestamp: true
