{
 "title": "Beehive service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Task parse success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total{status=\"200\",path=\"/api/v1/task/parse\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Task delegate success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total{status=\"200\",path=\"/api/v1/task\",method=\"POST\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Task prepare success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(beehive_task_prepare_success_total[$__interval])"
    }
   ]
  },
  {
   "title": "Work start",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total{status=\"200\",path=\"/api/v1/work/start\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Work finish",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(beehive_work_finish_summary_sum[$__interval])\n/\nrate(beehive_work_finish_summary_count[$__interval])"
    }
   ]
  }
 ]
}