"""add_task_context_table

Revision ID: 0073
Revises: 0072
Create Date: 2024-05-06 14:13:49.331054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0073'
down_revision = '0072'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_context',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('file', sa.Text()),
    sa.Column('entity', sa.Text()),
    sa.Column('potential_use', sa.Text()),
    sa.PrimaryKeyConstraint('id'),
    sa.Column('task_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='task_context_task_link'),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_context_task_link', 'task_context', type_='foreignkey')
    op.drop_table('task_context')
    # ### end Alembic commands ###
